%% MATLAB programming course for beginners, supported by Wagatsuma Lab@Kyutech 
%
% /* 
% The MIT License (MIT): 
% Copyright (c) 2021 Hiroaki Wagatsuma and Wagatsuma Lab@Kyutech
% 
% Permission is hereby granted, free of charge, to any person obtaining a
% copy of this software and associated documentation files (the
% "Software"), to deal in the Software without restriction, including
% without limitation the rights to use, copy, modify, merge, publish,
% distribute, sublicense, and/or sell copies of the Software, and to permit
% persons to whom the Software is furnished to do so, subject to the
% following conditions:
% 
% The above copyright notice and this permission notice shall be included
% in all copies or substantial portions of the Software.
% 
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
% OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
% MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
% NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
% DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
% OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
% USE OR OTHER DEALINGS IN THE SOFTWARE. */
%% Specifications and requirements
% # @Time    : 2021-5-26 
% # @Author  : Hiroaki Wagatsuma
% # @Site    : https://github.com/hirowgit/1B1_matlab_signal_analysis_course
% # @IDE     : MATLAB R2018a
% # @File    : lec3D_B1_flatPlane_Plus.m

%%  Main program
% clear all
dimN=3;

dN=5;
Fig1pos= [50 1200];
FigSize=1000*ones(1,2);

% ~~~~~~~~~MakeQTMovie <initialize> (start)~~~~~~~~~~~~~~
% You need to place "MakeQTMovie.m" (c) Copyright Malcolm Slaney, Interval Research, March 1999.
% in the same folder of this file

Flag_write_Movie=1;
Nm=1; % the serial number of the movie
ms_size=[480 360]; % the movie screen size
ms_size=FigSize; % the movie screen size

f_folder='movie'; % the output folder of the movie
if ~isdir(f_folder); mkdir(f_folder); end
f_prefix='outputMoviePlane_k_'; % the output file name
if Flag_write_Movie == 1
    MovieFileName = strcat(f_prefix,num2str(Nm),'.mov');
    fprintf('Creating the movie file %s.\n', fullfile(f_folder,MovieFileName));
    MakeQTMovie('start',fullfile(f_folder,MovieFileName));
    MakeQTMovie('size', ms_size);
    MakeQTMovie('quality', 1.0);
%     fps = 10;
  fps = 30;
end
% ~~~~~~~~~MakeQTMovie (end)~~~~~~~~~~~~~~



posDot=rand(dimN,dN);

figNum=1;
figure(figNum); clf
plot3(posDot(1,:),posDot(2,:),posDot(3,:),'.', 'MarkerSize',32);
grid on;
set(figNum,'Position',[Fig1pos FigSize]);
axis equal;

% making a test data to reconstruct a flat plane
dN=150;

scaleM=100; 
PatN=1; % PatN=3;
constN=1;
dimNt=dimN-constN;
rangVari=10; % range of Variance

basePos=scaleM.*(2*rand(dimNt,PatN)-1); % base Position
basePos=zeros(2,1);
rangeSpOccp=scaleM*0.1;
genPos2D=basePos+rangeSpOccp.*rand(dimNt,dN); gP2D=genPos2D;
genGrad=rangVari*rand(dimNt,PatN);  % a, b
genResidual=rangVari*rand(constN,PatN);  % c
genConst=-scaleM*rand(constN,PatN);  % d
% genConst=0;  % d

% genRd=rangeSpOccp.*rand(1,dN);
funcP=sum(repmat(genGrad,[1,dN]).*genPos2D)+repmat(genConst,[1,dN]);

% ax+by+cz+d=0;  
% (a/c)x+(b/c)y+z+(d/c)=0; => cf[2]*x+cf[3]*y+z+cf[1]=0; 
% => z=-(cf[2]*x+cf[3]*y+cf[1])/c
genRd=-funcP./genResidual;
genPos3D=[genPos2D;genRd];

figNum=figNum+1;
figure(figNum); clf
plot3(genPos3D(1,:),genPos3D(2,:),genPos3D(3,:),'.', 'MarkerSize',32);
grid on;
set(figNum,'Position',[Fig1pos FigSize]);
axis equal;

for my_az=-90:1:90
    figure(figNum);
    view(my_az,30);
    drawnow;
    % ~~~~~~~~~MakeQTMovie <add a frame> (start)~~~~~~~~~~~~~~
    if Flag_write_Movie == 1
        MakeQTMovie('addfigure');
    end
    % ~~~~~~~~~MakeQTMovie (end)~~~~~~~~~~~~~~
end

[caz,cel] = view()

% ~~~~~~~~~MakeQTMovie  <finalize> (start)~~~~~~~~~~~~~~
if Flag_write_Movie == 1
    MakeQTMovie('framerate', fps);
    MakeQTMovie('finish');
    strMessage=sprintf('Please find the generated mov file in the folder "%s" as filename "%s"',f_folder,MovieFileName);
    disp(strMessage);
end
% ~~~~~~~~~MakeQTMovie (end)~~~~~~~~~~~~~~




% ~~~~~~~~~MakeQTMovie <comment>~~~~~~~~~~~~~~
% The generated mov file is recommended to open QuickTime Player 7 in the first place and resave a new mov file by the player.
% The new mov file generated by the player can be opened with a recent version of the QuickTime Player.

% ~~~~~~~~~MakeQTMovie (end)~~~~~~~~~~~~~~